### ISSUE TITLE
Add `-tags=nomsgpack` to build invocation in Dockerfile

### ISSUE THREAD

**Issue by knightpp** [knightpp/alias-server#10]
We apparently do not use msgpack, so we can disable it to save some space.

**Comment by alexproskurov** [comment]
@knightpp how to add this tag in Dockerfile?

**Comment by knightpp** [comment]
In Dockerfile we have https://github.com/knightpp/alias-server/blob/ff5447b3b9f926790e57239be108e8058d36aee3/Dockerfile#L15 this line that builds executable with Go compiler. You can run `go help build` to see how to pass tags to the build.
